---
title: "Interfaz de usuario"
---

## Interfaz de Windows 10.

### El escritorio.
### Menú inicio.
### Barra de tareas.
### Vista de tareas.
### Iconos del sistema.
### Elementos básicos de las ventanas.
#### Organizar ventanas.
### Explorador de archivos.
#### Operaciones con archivos.
#### Búsqueda.
### Centro de actividades.
### Configuración.
### Cuentas locales y de Microsoft.
### Reinicio seguro.
### Administrador de tareas.
### Restaurar sistema.

## Interfaces de otros sistemas operativos.

### El escritorio.
### Menú inicio.
### Barra de tareas.
### Vista de tareas.
### Iconos del sistema.
### Elementos básicos de las ventanas.
#### Organizar ventanas.
### Explorador de archivos.
#### Operaciones con archivos.
#### Búsqueda.
### Centro de actividades.
### Configuración.
### Cuentas locales.
### Administrador de tareas.

## Fundamentos de amenazas y ataques informáticos
En los tiempos modernos, cuya velocidad de cambio, modos de obtener información y la manera en la que esta fluye de un punto a otro incluso del planeta, esa avidez del usuario actual por compartir absolutamente todo lo que realiza en su vida diaria, laboral, e incluso lúdica ha abierto la puerta para otro tipo de ataques que comprometan la seguridad personal y económica de las personas. Estamos constantemente conectados a Internet, y eso no deja mucha brecha para la privacidad. Sin embargo, lo peor no es perder la intimidad, sino perder miles o millones de pesos para el sector empresarial, nuestras cuentas bancarias, la producción intelectual, etc. 

Existen muchos tipos de ataques informáticos, de los cuales se enumeran algunos a continuación. Si queremos saber cómo estar seguros, debemos primero conocer cómo nos atacan.

### Ataque Denial of Service (DoS)
Evita el acceso a un sitio, es la denegación de servicio causada por un tráfico inusitado a servidores, lo que logra saturarlo. Pueden distinguirse ciertos síntomas, como la lentitud de carga de un sitio o incluso la imposibilidad de acceder.

#### Tear Drop Attack
Envío de paquetes de datos con superposición y cargas útiles de gran tamaño. Así, el servidor no puede ensamblar dichos paquetes y se bloquea o reinicia.

#### Smurf
Se envía una enorme cantidad de solicitudes de eco ICMP (_ping_) a la dirección _broadcast_ con una dirección falsa, lo que causa que el propio router envíe la transmisión IP a todos los equipos, los cuales responden el ECHO. Si la cantidad es grande, la red se satura. 

#### SYN Flood
La inundación SYN consiste en que el atacante se comunica con un servidor mediante una dirección de remitente falsa, enviando paquetes TCP/SYN. El servidor responde con SYN/ACK y al no recibir respuesta el servidor se queda semiabierto, esperando y sin la posibilidad de atender otras peticiones.

#### Land Attack
Se envían paquetes SYN falsificados que confunden al objetivo y causan su bloqueo.

#### Jolt DoS
Se envían fragmentos ICMP de tal manera que el objetivo no puede volver a armarlos, causando un aumento de uso de CPU.

#### Fraggie DoS
Es similar al _Smurf_, pero en lugar de IMCP son paquetes UDP.

### Ping Flood
Es simple, se basa en el envío masivo de _pings_ desde un origen UNIX con un ancho de banda superior al de la víctima.

### Ping de la Muerte
El atacante envía un paquete ICMP de más de 65,536 bytes. El sistema operativo simplemente no sabe que hacer con él y colapsa. Es ya obsoleto, pues en la actualidad simplemente se ignoran dichos paquetes.

### Denegación de Servicio Distribuido (DDoS)
Se le conoce como distribuido ya que utiliza varios equipos para el envío masivo de correos electrónicos, datos, spam, publicidad y todo lo que ocasione tráfico desmesurado.

### Escaneo de puertos
Consiste en enviar mensajes a cada puerto de un equipo conectado a una red. Esto con el fin de saber qué puertos se encuentran abiertos y buscar vulnerabilidades en los mismos.

### ARP Spoofing
Implica clonar una dirección MAC en redes que utilizan ARP (Adress Resolution Protocol, responsable de encontrar la dirección de hardware que corresponde a cierta dirección IP) y «escuchar» los datos que fluyen por ahí e incluso detener dicho flujo.

#### Inundación MAC
Envío masivo de paquetes MAC para saturar la memoria del switch y causar que se capturen paquetes de información.

#### Envenenamiento de caché DNS
Enviar datos de almacenamiento falsos a la caché para mejorar el rendimiento, haciéndose pasar por auténticos.

#### IP Spoofing
Suplantación de la dirección IP, con el fin de esconder la identidad original o hacerse pasar por otro.

### FTP Bounce
Conexión a servidores FTP y envío de archivos a otras máquinas mediante el comando PORT a través de _firewalls_ que lo permiten. Es ya obsoleto.

### TCP Session Hijacking
Tomar la sesión TCP al principio de la misma y suplantar a uno de los que se estaban comunicando.

### Ataque Man-In-The_Middle
Intercepción de cierto modo de comunicación por una entidad que se coloca entre los dos interlocutores. Por ejemplo, una máquina que se encuentra entre nuestro navegador y el servidor del banco, tratando de obtener nuestros datos bancarios.

### Ingeniería social
Manipulación de las personas para que estas renuncien de manera voluntaria a la privacidad y la salvaguarda de sus datos.

### OS Finger Printing
Identificar el sistema operativo de un equipo con la intención de saber qué tipo de ataque lanzar.

#### Activa
Enviar paquetes diseñados especialmente para analizar el tipo de respuesta del equipo y determinar el SO.

#### Pasiva
Rastrear el comportamiento de una máquina para detectar sus sistema operativo.

### KeyLoggers
Por lo general es software que registra las teclas presionadas en una máquina sin notificar al usuario, ya que se ejecuta en segundo plano.

### ICMP Tunneling
Entra como un mensaje IMCP a través del firewall, que por defecto no lo bloquea y establece un canal de comunicación cifrado y oculto entre dos computadoras utilizando _pings_.

### LOKI
Es un programa utilizado para demostrar que los datos pueden transmitirse de manera secreta si se esconden en el tráfico de cargas no útiles, como por ejemplo, un ping. Se utiliza como puerta trasera en sistemas UNIX.

### Ataque de predicción de secuencia TCP
El atacante espera y monitoriza la comunicación entre dos máquinas, con la intención de predecir el número de secuencia que sigue. Corta la comunicación entre ellas colapsando a una y suplantándola con su misma IP y enviando el número que debería seguir. Así la segunda máquina no se da cuenta de la usurpación y queda proclive a la inyección de datos maliciosos o a otorgar acceso al atacante.

### Ataques a aplicaciones web
En la actualidad, la mayoría de la información se encuentra almacenada en páginas web. Contra ellas se lanzan los siguientes ataques:

#### Inyección SQL
Ataque mediante el aprovechamiento de las vulnerabilidades de la capa de la base de datos.

#### Cross-Site Request
Transmisión de comandos o datos no autorizados por parte de un usuario en el que el sitio confía. Dicha confianza se entiende por el navegador que utiliza el usuario.

#### Envenenamiento de _cookies_
Modificación de los contenidos de una cookie para robar la identidad de un usuario.

#### Robo de cookies
Se realiza por medio de Javascript (script del lado del cliente), consiguiendo que al hacer clic en un enlace, el script busque las cookies asociadas al sitio y las envíe al atacante por medio de correo, por ejemplo.

#### Web Defacement
Modificación del contenido de un sitio web o su total sustitución por otro.

#### Buffer Overflow
Almacenamiento de datos en un búfer por fuera de memoria para desbordarlo. Los datos sobrepasan la capacidad y comienzan a ocupar espacios reservados para variables de proceso o datos de control del programa. Puede causar la falla catastrófica de la aplicación o una violación del sitio.

#### Navegación forzada
Entrar de manera forzada a todos los recursos accesibles de un sitio aunque no sean visibles y no haya referencia a los mismos. Pueden ser logs, archivos de respaldo o de configuración que puedan contener datos como contraseñas, por ejemplo.

#### División de respuesta HTTP
El atacante pasa datos maliciosos a la aplicación y esta los incluye en un encabezado HTTP, abriendo la puerta para suplantación o el Cross-Site Request.

#### Defectos de inyección
Se refieren a aplicaciones web que utilizan un intérprete de scripts (Perl o Python) o bases de datos como SQL, llamadas al sistema o el uso de programas externos a través del shell. Un atacante podría incluir código malicioso en algún script y ejecutarlo.

### Malware
Es una forma abreviada de _software malicioso_ e incluye virus, gusanos, troyanos, rootkits,  spyware, etc. Es código creado con la finalidad de dañar.

#### Virus
Programa informático que tiene la capacidad de reproducirse para infectar cualquier computadora después de propagarse por medio de internet, una red, memorias SD o USB. Debe unirse a otro programa informático y corrompen o dañan archivos.

#### Gusanos
También pueden replicarse aunque lo hacen principalmente por medio de la red. No necesitan unirse a otro programa y sus daños van más bien por el lado de consumir ancho de banda.

#### RootKit
Software diseñado para tomar los privilegios de administrador sobre un sistema sin ser detectado. El propósito es realizar operaciones maliciosas y se instalan incluso en la bios, hipervisores, cargadores de arranque o el kernel.

#### Troyanos
No se reproduce, pero se instala usualmente bajo permiso del usuario al hacerse pasar por software inocuo o benéfico. Permite el acceso al equipo.

### Adware
Es software que descarga o reproduce publicidad en sitios que visita el usuario o incluso en los programas instalados que utiliza de manera local.

### Spyware
Espía las acciones de un usuario en su computadora, encendiendo la cámara web o recolectando las teclas que presiona, los archivos que crea o los sitios que visita.

### Phishing
Extraer datos sensibles o comprometedores del usuario haciéndose pasar por una entidad de confianza.

### Medidas de seguridad
- Aplicación de filtrado de router
- Bloquear direcciones IP sin usar
- Permitir el acceso a la red solo al tráfico deseado
- Deshabilitar servicios de red innecesarios
- Actualización de antivirus regularmente
- Tener una muy buena política de contraseñas
- Limitar la cantidad de ancho de banda de la red
- Uso de la red de filtrado de acceso
- No abrir ningún correo sin remitente o que este sea desconocido. Incluso no abrir ninguno del cual se desconozca su intención o motivo o sea inesperado, aún conociendo al remitente.
- Implementar certificados de autenticación.
- Bloquear cualquier puerto innecesario.



## Aplicaciones.
